server:
  port: 8088

spring:
  application:
    name: reto-bbva

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
