-- Tabla principal del modulo cliente.

CREATE TABLE cliente (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    nombres              VARCHAR(100) NOT NULL,
    apellidos            VARCHAR(100) NOT NULL,
    numero_documento     VARCHAR(20)  NOT NULL,
    email                VARCHAR(150) NOT NULL,
    telefono             VARCHAR(20),
    estado               VARCHAR(20)  NOT NULL,
    -- Las gestiona JPA Auditing (@CreatedDate / @LastModifiedDate)
    fecha_creacion       TIMESTAMP    NOT NULL,
    fecha_actualizacion  TIMESTAMP    NOT NULL,

    CONSTRAINT pk_cliente PRIMARY KEY (id),
    -- Ambos identifican de forma unica al cliente en el negocio
    CONSTRAINT uk_cliente_numero_documento UNIQUE (numero_documento),
    CONSTRAINT uk_cliente_email UNIQUE (email),
    CONSTRAINT ck_cliente_estado CHECK (estado IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO'))
);
