-- Traza de negocio del modulo auditoria, escrita solo por el listener de eventos.

CREATE TABLE audit_log (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    entidad    VARCHAR(50) NOT NULL,
    entidad_id BIGINT      NOT NULL,
    accion     VARCHAR(20) NOT NULL,
    -- La gestiona JPA Auditing (@CreatedDate)
    fecha      TIMESTAMP   NOT NULL,

    CONSTRAINT pk_audit_log PRIMARY KEY (id),
    CONSTRAINT ck_audit_log_accion CHECK (accion IN ('CREADO', 'ACTUALIZADO', 'ELIMINADO'))
);

CREATE INDEX ix_audit_log_entidad_id ON audit_log (entidad_id);
